base_url = "https://bishalbagale.com.np"
title = "bishalbagale"
description = ""
generate_feed = true
build_search_index = false
theme = "after-dark"
[markdown]

highlight_code = true
taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
    ]
[extra]
author = "B.Bagale"
after_dark_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/blogs", name = "Blogs"},
    {url = "$BASE_URL/poems", name = "Show-Off"},
    {url = "$BASE_URL/darlings", name = "Darlings"},
 
  
    ]

after_dark_title = "Blogs"
