base_url = "https://bishalbagale.com.np"
title = "bishalbagale"
description = ""
generate_feed = true
build_search_index = false
theme = "after-dark"

taxonomies = [
 
    {name = "tags", feed = true},
]
[markdown]

highlight_code = true

[extra]
author = "B.Bagale"
after_dark_menu = [
    {url = "$BASE_URL/", name = "home"},
    {url = "$BASE_URL/blogs", name = "blogs"},
    {url = "$BASE_URL/tags", name = "tags"},

 
    ]



